### PR TITLE
Human Ontology and Human Gene Annotation Databases

### PR DESCRIPTION
**Pull request by ceefour**
Refs https://github.com/opencog/agi-bio/issues/33
Cc @AmeBel

### CODE REVIEW

**Comment by AmeBel** [comment]
@eddiemonroe please review and merge

**Comment by AmeBel** [comment]
If I am not mistaken, *.neo4j.tar.xz are neo4j dumps, right ?

please remove the binaries and only keep keep the readme update.

**Comment by ceefour** [comment]
@AmeBel Yes, these are neo4j dumps, which are convenient to use as-is, without needing to reimport from `scm` files.

**Comment by ceefour** [comment]
@AmeBel only README is left, as requested

**Pull request merged**
