### PR TITLE
MSigDB 5.0 in Scheme file

### PR DESCRIPTION
**Pull request by ceefour**
MSigDB 5.0 in Scheme file
Refs https://github.com/opencog/agi-bio/issues/33
Cc @AmeBel

### CODE REVIEW

**Comment by AmeBel** [comment]
@eddiemonroe please review and merge

**Comment by eddiemonroe** [comment]
@AmeBel, should we have these and the other bio datasets in a "bio" directory?

What's the reason for the .xy extensions?

(also re: #36)

**Comment by ceefour** [comment]
tar.xz files are compressed using xz (tar -J).

The 19 MB compressed file when extracted is about 200 MB.

**Comment by ceefour** [comment]
(Btw the filesize reference above is about the GO dataset, the MSigDB has much higher compression ratio)

**Comment by AmeBel** [comment]
Hi @ceefour,

I have moved the binaries to http://buildbot.opencog.org/downloads/. so will you remove them and create a pull request with the updated readme only?

Thanks

**Comment by ceefour** [comment]
@AmeBel only README is left, as requested

**Comment by AmeBel** [comment]
Thanks

**Pull request merged**
